sudo: required

services:
  - docker

language: bash

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t ${DOCKER_IMAGE} .
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin cloud.canister.io:5000
      docker push ${DOCKER_IMAGE}
    fi
