version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1

jobs:
  test:
    docker:
      - image: cimg/openjdk:8.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  publish:
    docker:
      - image: cimg/openjdk:8.0
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Build Application
          command: ./gradlew installDist
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - run:
          name: Init Image Tag Environment Variable
          command: |
            echo "export DOCKER_IMAGE_TAG=${CIRCLE_PROJECT_REPONAME}_0.0.<< pipeline.number >>" >> "$BASH_ENV"
            echo "export DOCKER_IMAGE_TAG_LATEST=${CIRCLE_PROJECT_REPONAME}_latest" >> "$BASH_ENV"
      - run:
          name: Build Image
          command: docker build -t ${DOCKERHUB_USERNAME}/${DOCKERHUB_REGISTRY}:${DOCKER_IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/${DOCKERHUB_REGISTRY}:${DOCKER_IMAGE_TAG_LATEST} .
      - run:
          command: |
            echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
            docker push --all-tags ${DOCKERHUB_USERNAME}/${DOCKERHUB_REGISTRY}
          name: Publish Image

  deploy:
    docker:
      - image: cimg/base:2024.06
    resource_class: small
    steps:
      - checkout
      - kubernetes/install-kubectl:
          kubectl-version: v1.30.1
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run:
          name: K8 Build Kustomize App Manifest
          command: kubectl kustomize k8 -o k8/${CIRCLE_PROJECT_REPONAME}.yaml
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          watch-rollout-status: true
          watch-timeout: 2m
          resource-file-path: k8/${CIRCLE_PROJECT_REPONAME}.yaml
          resource-name: deployment/${CIRCLE_PROJECT_REPONAME}-deployment
          namespace: ${CIRCLE_PROJECT_REPONAME}
          show-kubectl-command: true

workflows:
  build-and-publish:
    jobs:
      #- test
      - publish:
          name: Build and Publish Image
          context:
            - docker-hub-creds
      #requires:
      #- test
      - hold:
          name: Approve deployment
          type: approval
          requires:
            - Build and Publish Image
      - deploy:
          name: Deploy
          context:
            - k8-cluster
          requires:
            - Approve deployment
