apiVersion: apps/v1
kind: Deployment
metadata:
  name: taki-deployment
  namespace: taki
  labels:
    app: taki-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taki-app
  template:
    metadata:
      labels:
        app: taki-app
    spec:
      containers:
        - name: taki-app
          image: jhshadi/my-apps
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
          resources:
            requests:
              memory: "128M"
              cpu: "250m"
            limits:
              memory: "256M"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
