apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taki-ingress
  namespace: taki
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "taki.jhshadi.dev"
      secretName: cert-taki-https-secret
  rules:
    - host: taki.jhshadi.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taki-service
                port:
                  number: 9000
