apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taki-ingress
  namespace: taki
spec:
  ingressClassName: nginx
  rules:
    - host: taki.jhshadi.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taki-service
                port:
                  number: 9000
