apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - ingress.yaml
namespace: taki
images:
  - name: jhshadi/my-apps
    newName: jhshadi/my-apps
    newTag: taki_latest